server:
  port: 7002

eureka:
  instance:
    hostname: eureka7002.com

  client:
    register-with-eureka: false # eureka-server是不需要自己注册自己的
    fetchRegistry: false  # 我们注册中心不需要自己获取服务注册列表
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka  #注册中心地址,被Eureka-client使用的。20220522：eureka的访问地址
